version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: deployment-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8088:80"
    depends_on:
      - ml-service-blue
  
  ml-service-blue:
    image: ml-service:v1.0.0 # Используем фиксированный тег для v1
    container_name: ml-service-blue
    build: .
    environment:
      MODEL_VERSION: v1.0.0
    expose:
      - "8080"