version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: deployment-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - ml-service-green # Зависит от новой версии
  
  ml-service-green:
    image: ml-service:v1.1.0 # Используем новый тег для v2
    container_name: ml-service-green
    build: .
    environment:
      MODEL_VERSION: v1.1.0 # Новая версия!
    expose:
      - "8080"